### ISSUE TITLE
summoner is broken in lts-12

### ISSUE THREAD

**Issue by peti** [commercialhaskell/lts-haskell#176] opened 2018-10-09 07:57 UTC
`summoner-1.0.6` has edited its Cabal file to exclude `relude-0.1.x` from being used as a build dependency -- but that is exactly the version Stackage LTS-12.x has. So now the package no longer compiles in an LTS-12.x environment.

I'm wondering what's going on?

Ping @ChShersh.

**Comment by ChShersh** [comment] 2018-10-09 08:07
@peti I used Hackage revisions to make `summoner` pass CI on Hackage matrix:

* https://matrix.hackage.haskell.org/#/package/summoner

You can see the details of the revision here:

* https://hackage.haskell.org/package/summoner-1.0.6/revisions/

Maybe those constraints are too strict and it's enough to have something like `relude >= 0.1.0 && < 0.3.0` 🤔

**Comment by ChShersh** [comment] 2018-10-09 09:32
@peti Sorry for inconvenience 👍 It's hard to keep track of all version bounds, especially when they weren't too strict at the beginning. I've updated revision again, so should be ok now.

**Comment by alexeyzab** [comment] 2018-10-09 16:38
I was able to build `summoner-1.0.6` with `lts-12.12`, seems like the issue is resolved, closing.

**Closed by alexeyzab** 2018-10-09 16:38 UTC
